class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app.title': 'Christmas Countdown',
      'countdown.days': 'DAYS',
      'countdown.hours': 'HOURS',
      'countdown.minutes': 'MINUTES',
      'countdown.seconds': 'SECONDS',
      'countdown.christmas': 'Christmas',
      'countdown.itsChristmas': "It's Christmas! 🎄",
      'countdown.yearComplete': 'of the year complete',
      'settings.title': 'Settings',
      'settings.yearSelector': 'Target Year',
      'settings.colorTheme': 'Color Theme',
      'settings.snowIntensity': 'Snow Intensity',
      'settings.musicVolume': 'Music Volume',
      'settings.customMusicUrl': 'Custom Music URL',
      'settings.notifications': 'Notifications',
      'settings.language': 'Language',
      'settings.share': 'Share Countdown',
      'settings.notificationOneWeek': '1 Week Before Message',
      'settings.notificationThreeDays': '3 Days Before Message',
      'settings.notificationOneDay': '1 Day Before Message',
      'themes.classic': 'Classic',
      'themes.winter': 'Winter',
      'themes.royal': 'Royal',
      'themes.candy': 'Candy',
      'themes.golden': 'Golden',
      'themes.icy': 'Icy',
      'themes.forest': 'Forest',
      'themes.sunset': 'Sunset',
      'themes.aurora': 'Aurora',
      'notifications.oneWeekDefault': '🎄 Only 1 week until Christmas!',
      'notifications.threeDaysDefault': '🎅 Just 3 days left until Christmas!',
      'notifications.oneDayDefault': '🎁 Christmas is tomorrow!',
      'tree.decorationProgress': 'Tree Decoration Progress',
    },
    'es': {
      'app.title': 'Cuenta Regresiva de Navidad',
      'countdown.days': 'DÍAS',
      'countdown.hours': 'HORAS',
      'countdown.minutes': 'MINUTOS',
      'countdown.seconds': 'SEGUNDOS',
      'countdown.christmas': 'Navidad',
      'countdown.itsChristmas': '¡Es Navidad! 🎄',
      'countdown.yearComplete': 'del año completo',
      'settings.title': 'Configuración',
      'settings.yearSelector': 'Año Objetivo',
      'settings.colorTheme': 'Tema de Color',
      'settings.snowIntensity': 'Intensidad de Nieve',
      'settings.musicVolume': 'Volumen de Música',
      'settings.customMusicUrl': 'URL de Música Personalizada',
      'settings.notifications': 'Notificaciones',
      'settings.language': 'Idioma',
      'settings.share': 'Compartir Cuenta Regresiva',
      'settings.notificationOneWeek': 'Mensaje 1 Semana Antes',
      'settings.notificationThreeDays': 'Mensaje 3 Días Antes',
      'settings.notificationOneDay': 'Mensaje 1 Día Antes',
      'themes.classic': 'Clásico',
      'themes.winter': 'Invierno',
      'themes.royal': 'Real',
      'themes.candy': 'Dulce',
      'themes.golden': 'Dorado',
      'themes.icy': 'Helado',
      'themes.forest': 'Bosque',
      'themes.sunset': 'Atardecer',
      'themes.aurora': 'Aurora',
      'notifications.oneWeekDefault': '🎄 ¡Solo falta 1 semana para Navidad!',
      'notifications.threeDaysDefault': '🎅 ¡Solo quedan 3 días para Navidad!',
      'notifications.oneDayDefault': '🎁 ¡Mañana es Navidad!',
      'tree.decorationProgress': 'Progreso de Decoración del Árbol',
    },
    'fr': {
      'app.title': 'Compte à Rebours de Noël',
      'countdown.days': 'JOURS',
      'countdown.hours': 'HEURES',
      'countdown.minutes': 'MINUTES',
      'countdown.seconds': 'SECONDES',
      'countdown.christmas': 'Noël',
      'countdown.itsChristmas': "C'est Noël! 🎄",
      'countdown.yearComplete': "de l'année complète",
      'settings.title': 'Paramètres',
      'settings.yearSelector': 'Année Cible',
      'settings.colorTheme': 'Thème de Couleur',
      'settings.snowIntensity': 'Intensité de la Neige',
      'settings.musicVolume': 'Volume de la Musique',
      'settings.customMusicUrl': 'URL de Musique Personnalisée',
      'settings.notifications': 'Notifications',
      'settings.language': 'Langue',
      'settings.share': 'Partager le Compte à Rebours',
      'settings.notificationOneWeek': 'Message 1 Semaine Avant',
      'settings.notificationThreeDays': 'Message 3 Jours Avant',
      'settings.notificationOneDay': 'Message 1 Jour Avant',
      'themes.classic': 'Classique',
      'themes.winter': 'Hiver',
      'themes.royal': 'Royal',
      'themes.candy': 'Bonbon',
      'themes.golden': 'Doré',
      'themes.icy': 'Glacé',
      'themes.forest': 'Forêt',
      'themes.sunset': 'Coucher de Soleil',
      'themes.aurora': 'Aurore',
      'notifications.oneWeekDefault': '🎄 Plus qu\'1 semaine avant Noël!',
      'notifications.threeDaysDefault': '🎅 Plus que 3 jours avant Noël!',
      'notifications.oneDayDefault': '🎁 Noël c\'est demain!',
      'tree.decorationProgress': 'Progrès de Décoration de l\'Arbre',
    },
    'nl': {
      'app.title': 'Kerstaftelling',
      'countdown.days': 'DAGEN',
      'countdown.hours': 'UREN',
      'countdown.minutes': 'MINUTEN',
      'countdown.seconds': 'SECONDEN',
      'countdown.christmas': 'Kerstmis',
      'countdown.itsChristmas': 'Het is Kerstmis! 🎄',
      'countdown.yearComplete': 'van het jaar voltooid',
      'settings.title': 'Instellingen',
      'settings.yearSelector': 'Doeljaar',
      'settings.colorTheme': 'Kleurenthema',
      'settings.snowIntensity': 'Sneeuw Intensiteit',
      'settings.musicVolume': 'Muziekvolume',
      'settings.customMusicUrl': 'Aangepaste Muziek-URL',
      'settings.notifications': 'Meldingen',
      'settings.language': 'Taal',
      'settings.share': 'Aftelling Delen',
      'settings.notificationOneWeek': 'Bericht 1 Week Ervoor',
      'settings.notificationThreeDays': 'Bericht 3 Dagen Ervoor',
      'settings.notificationOneDay': 'Bericht 1 Dag Ervoor',
      'themes.classic': 'Klassiek',
      'themes.winter': 'Winter',
      'themes.royal': 'Koninklijk',
      'themes.candy': 'Snoep',
      'themes.golden': 'Gouden',
      'themes.icy': 'IJzig',
      'themes.forest': 'Bos',
      'themes.sunset': 'Zonsondergang',
      'themes.aurora': 'Noorderlicht',
      'notifications.oneWeekDefault': '🎄 Nog maar 1 week tot Kerstmis!',
      'notifications.threeDaysDefault': '🎅 Nog maar 3 dagen tot Kerstmis!',
      'notifications.oneDayDefault': '🎁 Morgen is het Kerstmis!',
      'tree.decorationProgress': 'Versiering Voortgang',
    },
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static AppLocalizations of(String languageCode) => AppLocalizations(languageCode);
}
