class HolidayFactsService {
  static final List<String> dailyFacts = [
    "Christmas trees were originally brought indoors during winter to remind people that spring would return.",
    "The tradition of hanging stockings comes from Saint Nicholas, who would secretly leave gold coins in stockings left by the fireplace.",
    "Rudolph the Red-Nosed Reindeer was created in 1939 as a marketing tool for Montgomery Ward.",
    "The first Christmas card was sent in 1843 by Sir Henry Cole in England.",
    "In the UK, it's traditional to pull Christmas crackers at the dinner table, which contain small gifts and paper crowns.",
    "The poinsettia plant is named after Joel Roberts Poinsett, the first U.S. ambassador to Mexico.",
    "Christmas pudding is traditionally stirred by each family member while making a wish.",
    "The Christmas tree tradition was popularized in Germany and brought to England by Prince Albert.",
    "Candy canes were originally white and straight, used to keep children quiet during long Christmas services.",
    "The word 'Christmas' comes from the Old English 'Cristes Maesse,' meaning 'Christ's Mass.'",
    "In Finland, Christmas is called 'Joulu,' and the Christmas Peace has been declared annually since 1288.",
    "The tradition of Christmas caroling dates back to the Middle Ages.",
    "Mistletoe was considered sacred by the Druids and was used in winter celebrations.",
    "The first artificial Christmas tree was made from goose feathers in Germany.",
    "Christmas lights were first used on trees in the 17th century using candles.",
    "The average American family spends about 6 hours decorating their home for Christmas.",
    "In Sweden, Christmas is celebrated for 13 days, from December 13 to December 25.",
    "The tradition of leaving cookies and milk for Santa started in the 1930s.",
    "Christmas trees can live for up to 40 years in the wild.",
    "The most popular Christmas gift of all time is socks.",
    "In Japan, Christmas is celebrated as a secular holiday, and KFC is a popular Christmas dinner.",
    "The Christmas tree at Rockefeller Center in New York is typically 75 feet tall.",
    "Jingle Bells was originally written as a Thanksgiving song, not a Christmas song.",
    "The tradition of Christmas stockings originated from the legend of Saint Nicholas.",
    "In Iceland, Christmas is celebrated for 13 days, and each day has its own tradition.",
    "The first Christmas broadcast on radio was in 1906.",
    "Christmas decorations were originally made from natural materials like holly, ivy, and mistletoe.",
    "The Christmas tree tradition in America was popularized by President Franklin D. Roosevelt.",
    "In Mexico, Christmas celebrations include Las Posadas, a reenactment of Mary and Joseph seeking shelter.",
    "The word 'Noel' comes from the French word 'Noël,' meaning 'Christmas.'",
    "Christmas is celebrated on January 7 in some Orthodox Christian countries.",
    "The tradition of Christmas caroling was started by Charles Dickens' 'A Christmas Carol.'",
    "In Germany, gingerbread houses are a traditional Christmas decoration.",
    "The Christmas tree was first decorated with apples and nuts.",
    "Santa's reindeer were named in the poem 'A Visit from St. Nicholas' in 1823.",
    "The Christmas season is the busiest shopping season of the year.",
    "In Italy, Christmas is celebrated with a nativity scene called a 'presepio.'",
    "The tradition of Christmas bonuses started in the Victorian era.",
    "Eggnog was originally made with brandy and was considered a luxury drink.",
    "The Christmas tree symbolizes eternal life because it stays green year-round.",
    "In France, Christmas is called 'Noël,' and children leave out shoes instead of stockings.",
    "The first Christmas tree in America was set up in the 1700s by German settlers.",
    "Christmas crackers were invented in 1847 by a London sweet maker named Tom Smith.",
    "The tradition of Christmas pantomimes started in Italy during the 16th century.",
    "In Spain, Christmas is celebrated with a lottery called 'El Gordo.'",
    "The Christmas tree at the Vatican is typically 80 feet tall.",
    "The tradition of Christmas markets started in Germany in the 15th century.",
    "In Austria, Christmas is celebrated with a special bread called 'Stollen.'",
    "The first electric Christmas lights were used in 1880.",
    "Christmas is the most popular holiday for weddings in some countries.",
    "The tradition of Christmas gift-giving comes from the gifts given to Jesus by the Magi.",
    "In Poland, Christmas dinner traditionally includes 12 dishes, one for each apostle.",
    "The Christmas tree tradition was brought to America by German immigrants.",
    "The word 'Santa' comes from the Latin word 'Sanctus,' meaning 'holy.'",
    "In Norway, Christmas is celebrated with a special bread called 'Julekake.'",
    "The tradition of Christmas caroling was popular in medieval times.",
    "The first Christmas tree in the White House was set up in 1889.",
    "In Denmark, Christmas is celebrated with a special drink called 'Gløgg.'",
    "The Christmas tree at Trafalgar Square in London is a gift from Norway.",
    "The tradition of Christmas stockings comes from the legend of Saint Nicholas.",
    "In Belgium, Christmas is celebrated with a special chocolate called 'Praline.'",
    "The first Christmas parade was held in Philadelphia in 1920.",
    "In Greece, Christmas is celebrated with a special bread called 'Christopsomo.'",
    "The Christmas tree tradition symbolizes hope and renewal.",
    "In Portugal, Christmas is celebrated with a special cake called 'Bolo de Natal.'",
    "The tradition of Christmas gift-giving is practiced in over 100 countries.",
    "In Ireland, Christmas is celebrated with a special drink called 'Irish Coffee.'",
    "The first Christmas tree in Times Square was set up in 1912.",
    "In Hungary, Christmas is celebrated with a special soup called 'Fish Soup.'",
    "The Christmas tree at the Rockefeller Center has been a tradition since 1931.",
    "In Czech Republic, Christmas is celebrated with a special bread called 'Vánočka.'",
    "The tradition of Christmas caroling brings joy to millions of people worldwide.",
    "In Romania, Christmas is celebrated with a special bread called 'Cozonac.'",
    "The first Christmas tree in the United States was set up in 1747.",
    "In Slovakia, Christmas is celebrated with a special bread called 'Vianočka.'",
    "The Christmas tree tradition has been celebrated for over 500 years.",
    "In Slovenia, Christmas is celebrated with a special bread called 'Potica.'",
    "The tradition of Christmas gift-giving strengthens family bonds.",
    "In Croatia, Christmas is celebrated with a special bread called 'Pogača.'",
    "The Christmas tree at the Vatican is decorated with lights and ornaments.",
    "In Serbia, Christmas is celebrated with a special bread called 'Pogača.'",
    "The tradition of Christmas caroling dates back to the 13th century.",
    "In Bulgaria, Christmas is celebrated with a special bread called 'Pitka.'",
    "The Christmas tree tradition symbolizes the victory of light over darkness.",
    "In Ukraine, Christmas is celebrated on January 7 according to the Orthodox calendar.",
    "The first Christmas tree in London was set up in 1841.",
    "In Russia, Christmas is celebrated on January 7 according to the Orthodox calendar.",
    "The Christmas tree tradition brings families together to celebrate.",
    "In Belarus, Christmas is celebrated on January 7 according to the Orthodox calendar.",
    "The tradition of Christmas gift-giving is a way to show love and appreciation.",
    "In Moldova, Christmas is celebrated on January 7 according to the Orthodox calendar.",
    "The Christmas tree at the Rockefeller Center is lit with over 50,000 lights.",
    "In Georgia, Christmas is celebrated on January 7 according to the Orthodox calendar.",
    "The tradition of Christmas caroling brings communities together.",
    "In Armenia, Christmas is celebrated on January 6 according to the Armenian Apostolic Church.",
    "The Christmas tree tradition is celebrated in over 100 countries worldwide.",
    "In Ethiopia, Christmas is celebrated on January 7 according to the Ethiopian Orthodox Church.",
    "The first Christmas tree in Paris was set up in 1840.",
    "In Egypt, Christmas is celebrated by the Coptic Orthodox Church on January 7.",
    "The Christmas tree tradition symbolizes hope, joy, and renewal.",
    "In Lebanon, Christmas is celebrated with a special drink called 'Arak.'",
    "The tradition of Christmas gift-giving is a way to spread joy and happiness.",
    "In Syria, Christmas is celebrated with a special bread called 'Ma'amoul.'",
    "The Christmas tree at the Rockefeller Center is a symbol of hope and joy.",
    "In Palestine, Christmas is celebrated with a special bread called 'Ma'amoul.'",
    "The tradition of Christmas caroling is a way to spread holiday cheer.",
    "In Jordan, Christmas is celebrated with a special bread called 'Ma'amoul.'",
    "The Christmas tree tradition brings joy to millions of people worldwide.",
    "In Iraq, Christmas is celebrated with a special bread called 'Kleicha.'",
    "The first Christmas tree in Berlin was set up in 1841.",
    "In Saudi Arabia, Christmas is not officially celebrated, but some expats celebrate privately.",
    "The Christmas tree tradition symbolizes the birth of Jesus Christ.",
    "In United Arab Emirates, Christmas is celebrated by expatriates in shopping malls.",
    "The tradition of Christmas gift-giving is a way to express love and gratitude.",
    "In Qatar, Christmas is celebrated by expatriates in shopping malls.",
    "The Christmas tree at the Rockefeller Center attracts millions of visitors annually.",
    "In Bahrain, Christmas is celebrated by expatriates in shopping malls.",
    "The tradition of Christmas caroling is a way to bring communities together.",
    "In Kuwait, Christmas is celebrated by expatriates in shopping malls.",
    "The Christmas tree tradition is a symbol of hope and joy for many people.",
    "In Oman, Christmas is celebrated by expatriates in shopping malls.",
    "The first Christmas tree in Vienna was set up in 1814.",
    "In Yemen, Christmas is not officially celebrated due to religious reasons.",
    "The Christmas tree tradition brings families together to celebrate the holiday season.",
  ];

  static final List<String> dailyMessages = [
    "🎄 Today is a day to spread joy and kindness to everyone around you!",
    "❄️ The magic of Christmas is in the moments we share with loved ones.",
    "🎅 Remember to take time to appreciate the little things this holiday season.",
    "⛄ Spread Christmas cheer by doing something kind for someone today!",
    "🎁 The best gift you can give is your time and attention to those you love.",
    "🕯️ Let the light of Christmas guide you through the darkest days.",
    "🎵 Sing a Christmas carol and brighten someone's day!",
    "❤️ Christmas is a time to forgive, forget, and embrace those we love.",
    "✨ The spirit of Christmas lives in the hearts of those who believe.",
    "🌟 Make today count by spreading love and happiness to everyone you meet.",
    "🎀 Remember that the greatest gift is the gift of love.",
    "🔔 Let the bells of Christmas ring in your heart with joy and hope.",
    "🍪 Bake some cookies and share them with your neighbors!",
    "☃️ Build a snowman and remember the simple joys of childhood.",
    "🎊 Celebrate the season by decorating your home with love and care.",
    "💝 Give a gift from the heart, not from the wallet.",
    "🌲 Plant a tree and watch it grow, just like the spirit of Christmas.",
    "🎭 Watch a Christmas movie and enjoy the magic of the season.",
    "🎸 Play Christmas music and let it fill your home with joy.",
    "🕯️ Light a candle and make a wish for peace on earth.",
    "🎨 Create a Christmas craft with your family and friends.",
    "📖 Read a Christmas story and share it with someone you love.",
    "🎪 Attend a Christmas event and celebrate with your community.",
    "🎯 Set a goal to spread kindness every day this Christmas season.",
    "🎁 Volunteer at a local charity and make a difference in someone's life.",
    "🌟 Remember that you are a gift to the world.",
    "💫 Believe in the magic of Christmas and miracles will happen.",
    "🎄 Decorate your tree with love and watch it shine brightly.",
    "🎅 Be like Santa and give without expecting anything in return.",
    "⛄ Let the snow remind you of the purity and beauty of Christmas.",
    "🎵 Sing carols and spread Christmas cheer to everyone you meet.",
    "❤️ Open your heart to love and let it guide your actions.",
    "✨ The magic of Christmas is in the love we share with others.",
    "🌟 Shine brightly and let your light inspire others.",
    "🎀 Wrap your gifts with love and care.",
    "🔔 Ring the bells of joy and celebrate the season!",
    "🍪 Share cookies and hot cocoa with friends and family.",
    "☃️ Build memories that will last a lifetime.",
    "🎊 Celebrate the birth of Jesus and the hope he brings.",
    "💝 Give generously and watch the joy multiply.",
    "🌲 Appreciate the beauty of nature and the season.",
    "🎭 Enjoy the magic of Christmas movies and stories.",
    "🎸 Let Christmas music fill your heart with joy.",
    "🕯️ Light the way for others with your kindness.",
    "🎨 Create beauty and share it with the world.",
    "📖 Share stories of hope and inspiration.",
    "🎪 Celebrate with your community and build connections.",
    "🎯 Make a difference in someone's life today.",
    "🎁 Give the gift of time and attention.",
    "🌟 You are a star in someone's sky.",
    "💫 Believe in yourself and the magic of Christmas.",
  ];

  /// Get daily fact based on current date
  static String getDailyFact() {
    final now = DateTime.now();
    final dayOfYear = now.difference(DateTime(now.year, 1, 1)).inDays;
    final index = dayOfYear % dailyFacts.length;
    return dailyFacts[index];
  }

  /// Get daily message based on current date
  static String getDailyMessage() {
    final now = DateTime.now();
    final dayOfYear = now.difference(DateTime(now.year, 1, 1)).inDays;
    final index = dayOfYear % dailyMessages.length;
    return dailyMessages[index];
  }

  /// Get random fact
  static String getRandomFact() {
    final now = DateTime.now();
    final index = now.millisecondsSinceEpoch % dailyFacts.length;
    return dailyFacts[index];
  }

  /// Get random message
  static String getRandomMessage() {
    final now = DateTime.now();
    final index = now.millisecondsSinceEpoch % dailyMessages.length;
    return dailyMessages[index];
  }
}
